"""initial schema

Revision ID: 90e52b2c1f62
Revises: 
Create Date: 2025-12-01 23:47:50.140005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e52b2c1f62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('commence_time', sa.DateTime(), nullable=False),
    sa.Column('home_moneyline', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('away_moneyline', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('home_spread', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('home_spread_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('away_spread', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('away_spread_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_points', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('over_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('under_odds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'IN_PROGRESS', 'COMPLETED', name='gamestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('bet_type', sa.Enum('MONEYLINE', 'SPREAD', 'OVER_UNDER', name='bettype'), nullable=False),
    sa.Column('selection', sa.Enum('HOME', 'AWAY', 'OVER', 'UNDER', name='betselection'), nullable=False),
    sa.Column('odds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stake', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('potential_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'PUSH', name='betstatus'), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
